name: Python application

on: [push]

jobs:
  build:

    runs-on: fedora 31

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: GAM Frontend
      run: |
        pyinstaller gam.py --onefile
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
